#author agis daniels
#How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def main():	
	pows=[]
	append=pows.append
	for i in range(2,101):
		for x in range(2,101):
			append(i**x)
	myset=set(pows)
	print(len(myset))

if __name__=='__main__':
	main()
